/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/minchanpark/Documents/PJT/rkorea/modney_flutter_boilerproject/assets/images/login_apple.png)
  final login_apple = r'assets/images/login_apple.png';

  /// ![](/Users/minchanpark/Documents/PJT/rkorea/modney_flutter_boilerproject/assets/images/login_kakao.png)
  final login_kakao = r'assets/images/login_kakao.png';

  /// ![](/Users/minchanpark/Documents/PJT/rkorea/modney_flutter_boilerproject/assets/images/main_image.png)
  final main_image = r'assets/images/main_image.png';

  /// ![](/Users/minchanpark/Documents/PJT/rkorea/modney_flutter_boilerproject/assets/images/login_google.png)
  final login_google = r'assets/images/login_google.png';
}

class _SvgResources {
  const _SvgResources();
}
